language: ruby
rvm:
 - 1.8.7
 - 1.9.2

script: "rake spec"

branches:
  only:
      - master
      - /^issues\/.*$/

notifications:
  email:
    - arusso@berkeley.edu
env:
  - PUPPET_VERSION=2.7.22
  - PUPPET_VERSION=3.2.3
